apiVersion: apps/v1
kind: Deployment
metadata:
  name: launcher-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: launcher-operator
  template:
    metadata:
      labels:
        name: launcher-operator
    spec:
      serviceAccountName: launcher-operator
      containers:
        - name: launcher-operator
          image: quay.io/gastaldi/launcher-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 4
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 4
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "launcher-operator"