apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: launcher-operator
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    - serviceaccounts
    - processedtemplates.template.openshift.io
    verbs:
    - '*'
  - apiGroups:
    - template.openshift.io
    resources:
    - processedtemplates
    verbs: [ get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
    - ""
    - apps.openshift.io
    resources:
    - deploymentconfigs
    - deploymentconfigs/instantiate
    verbs: [ get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
    - route.openshift.io
    resources:
    - routes
    - routes/custom-host
    verbs: [ get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - launcher.fabric8.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list